version: "3.4"

services:

    login-server:
        build:
            context: login-server
            network: host
        image: mlb/login-server
        container_name: login-server
        ports:
            - "21986:22"
        volumes:
            - /var/login-server/authorized_keys:/etc/ssh/authorized_keys
            - /var/login-server/auth.log:/var/log/auth.log