version: "3.4"

services:

    login-server:
        build:
            context: <name>
            network: host
        image: mlb/<name>
        container_name: <name>
        ports:
            - "<port>:22"
        volumes:
            - /var/<name>/authorized_keys:/etc/ssh/authorized_keys
            - /var/<name>/auth.log:/var/log/auth.log